controller_list:
  - name: fake_scara_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_joint
      - elbow_joint
      - wrist_joint
  - name: fake_scara_drill_controller
    type: $(arg fake_execution_type)
    joints:
      - chuck_joint
initial:  # Define initial robot poses per group
  - group: scara_arm
    pose: initial_pose
  - group: scara_drill
    pose: drilling_start