controller_list:
  - name: scara_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_joint
      - elbow_joint
      - wrist_joint
  - name: scara_drill_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - chuck_joint

scara_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_joint
    - elbow_joint
    - wrist_joint
  gains:
    shoulder_joint:
      p: 100
      d: 35
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 25
      i: 1
      i_clamp: 1
    wrist_joint:
      p: 100000
      d: 1000
      i: 4000
      i_clamp: 1
scara_drill_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - chuck_joint
  gains:
    chuck_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1