scara_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_joint
    - elbow_joint
    - wrist_joint
  gains:
    shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
scara_drill_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - chuck_joint
  gains:
    chuck_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1